### PR TITLE
Restoring multimarkers examples

### PR DESCRIPTION
**Pull request by kalwalt**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**

It try to restore multimarkers examples.
**Can it be referenced to an Issue? If so what is the issue # ?**
There is not a specific issue but it is part of #402
**How can we test it?**

Test the learner.html and player.html inside `three.js/examples/multi-markers/examples/`
**Summary**

This PR not improve the multi-markers examples, it simply fix the url paths for the examples.
**Does this PR introduce a breaking change?**
No at all.
**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
Tested on desktop Ubuntu 20.04, the learner and player seems to work, But i can't assure and i will not work on that feature for now.
**Other information**
This feature was under development in the old repository by the original creator, we do a minimal restore but i personally i have not time to continue on this.

### CODE REVIEW

**Comment by kalwalt** [comment]
@nickw1 i merge this soon there is not needs to test (i have tested), as mentioned at the top this was under development and i'm not sure how we can continue. At least we can make this minimal restore but PR's are welcome to improve it!

**Comment by nickw1** [comment]
@kalwalt seems fine to merge in that case. I don't know so much about marker-based so I doubt I can work on it myself, but yes PRs would be welcome!

**Comment by kalwalt** [comment]
latest commit should fix https://github.com/AR-js-org/AR.js/pull/411

**Comment by kalwalt** [comment]
@nickw1 if you agree i will make a new release soon when i have time. Probably we can make a `3.4.0` release now?

**Comment by nickw1** [comment]
@kalwalt sounds good. I might just add some READMEs to the various location-based APIs, if that's OK - to ensure users are clear what is what. I think I will encourage people to use the `new-location-based` version if they want to use location-based with A-Frame, and then fall back to the older version if they have problems.

**Comment by nickw1** [comment]
@kalwalt OK have added the READMEs so I'm happy to release now if you are.

**Comment by kalwalt** [comment]
@nickw1 i will do it soon!

**Comment by nickw1** [comment]
@kalwalt ok great!

**Pull request merged**
