### PR TITLE
Webpack Build for AR.js

### PR DESCRIPTION
**Pull request by MikiDi**
:information_source: _This is a **draft** PR. Its aim is to provide a forum to discuss the changes introduced and seek some help in order to make the PR merge-ready._

## What kind of change does this PR introduce?
Webpack build-system instead of "`cat` build-system" :wink: , module-based code, usage of [andypotato's
artoolkit5-js](https://github.com/andypotato/artoolkit5-js) 

## Related issues
- #21 
- #68 

## Summary
In order to comfortably integrate this great library in a modern web application (React, Angular, Ember.js, ...) it would be nice to have AR.js provided as a **ES6 module** (while keeping support for browser `<script>` usage). Refactoring the library to also use import/export internally, has the additional (and arguably most important) advantage of **improved maintainability**.  
In order to achieve the above, I refactored the library to use imports/exports instead of relying on globals and introduced a build configuration for [webpack](https://webpack.js.org/). Since the [jsartoolkit5](https://github.com/artoolkitx/jsartoolkit5) library is somewhat [flawed](https://github.com/artoolkitx/jsartoolkit5/issues/69) when it comes to ES6 support, this PR depends on the work done by @andypotato in [artoolkit5-js](https://github.com/andypotato/artoolkit5-js) to make the library ES6-compatible.  

I started off with getting the regular (non-nft) build to work and feel like I'm quite far, but got somewhat stuck now. When running the [basic](https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/aframe/examples/marker-based/basic.html) example, the initialization process goes well, markers are detected when in view (it runs through [updateWithModelViewMatrix](https://github.com/MikiDi/AR.js/blob/0a69d3696fade29845702c67558c8aa79ab0ef8a/three.js/src/threex/arjs-markercontrols.js#L107)), but the gltf **model ( :t-rex: ) doesn't show**. When debugging I discovered the [A-Frame inspector](https://github.com/aframevr/aframe-inspector) (I have little prior experience with aframe/three.js). The weirdest thing is that when you run the example with the A-Frame inspector, everything works as expected! :open_mouth:  This leads me to suspect that there's a minor bug in the aframe/three.js related part, which perhaps can be easily solved with some more background knowledge ... I can't seem to figure it out ...
Before continuing work to get the NFT build going (and on a longer term refactor out the separate builds and code duplication between nft/non-nft ), I'd like to get this fixed ... Is this something you could help out with maybe @kalwalt @nicolocarpignoli ?

## Does this PR introduce a breaking change?
No. Functionality-wise, the end-result of this PR should do exactly the same as the current master build.

## How can we test it?
Host the [basic](https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/aframe/examples/marker-based/basic.html) example and use the  `aframe-ar.js` build from the [PR branch](https://github.com/MikiDi/AR.js/tree/webpack/aframe/build).
Add [A-Frame inspector](https://github.com/aframevr/aframe-inspector#specifying-inspector-build) and press `<ctrl> + <alt> + i` to inject the inspector (make sure to press :play_or_pause_button: )  
In order to make changes and rebuild:
```
npm install
```
```
npm run build:dev
```

## Device used for tests, version of OS and version of Browser
Desktop (webcam), Fedora 30, Firefox 74.0

### CODE REVIEW

**Comment by kalwalt** [comment]
@MikiDi :tada: :smile:  I am very interested on the ES6 support, It is on my to do list! The old `cat / make` system is not suitable anymore in my opinion. I will review your PR, also providing support/help if needed. But i need a bit of time for testing...

**Comment by kalwalt** [comment]
Not tested but maybe the problem is in this line:     https://github.com/MikiDi/AR.js/blob/0a69d3696fade29845702c67558c8aa79ab0ef8a/three.js/src/threex/arjs-context.js#L262
We had this problem with the new jsartoolkit5 lib, and we need to uncomment the multiplication because an internal change in the Artoolkit5 C++ code. See https://github.com/AR-js-org/AR.js/pull/60 https://github.com/AR-js-org/AR.js/issues/59 https://github.com/AR-js-org/AR.js/issues/68

**Comment by MikiDi** [comment]
That did it :ok_hand: thx a lot. Will get back here when the NFT build is working :-)

**Comment by kalwalt** [comment]
> That did it  thx a lot. Will get back here when the NFT build is working :-)

I was quite sure was that... But have you a working version of artoolkit5-js with NFT?

**Comment by MikiDi** [comment]
As I said ... haven't gotten to that yet (but shouldn't be too hard from what I can see now :thinking:  ...). Looks like [artoolkit5-js](https://github.com/andypotato/artoolkit5-js/blob/master/src/ARController.js#L274) has support for NFT though? Do you think I'm missing something?

**Comment by kalwalt** [comment]
> As I said ... haven't gotten to that yet (but shouldn't be too hard from what I can see now  ...). Looks like [artoolkit5-js](https://github.com/andypotato/artoolkit5-js/blob/master/src/ARController.js#L274) has support for NFT though? Do you think I'm missing something?

As i know and as i can see from the code is not completely implemented. Not all athe methods are available yet, For example the **addNFTMarker** is not, and other...

**Comment by kalwalt** [comment]
see https://github.com/andypotato/artoolkit5-js/blob/8ea81fc8e6e722538c602fdc99c9be6ccbf166b4/src/ARToolkit.js#L130-L132 the addNFTMarker is empty

**Comment by kalwalt** [comment]
I tested on desktop some examples (threejs/examples/basic.html and aframe/examples/marker-based/basic.html) and they works. 
One thing: Your PR is aligned to the dev or the master branch? Because you are requesting to merge directly into the `master`, but normally we accept PR to the `dev` branch.
I also noted that there is not this multiplication ( i added again because we missed during the upgrade to v3.0.0, i recntly merged on the dev with PR #60 ) 
https://github.com/AR-js-org/AR.js/blob/93cbc7fdbc4d0350c8735d1972993d5672d17014/three.js/src/threex/threex-armarkercontrols.js#L119-L121
This was necessary before, ( without this you need to shift the model on the z axis and not on y axis) but not with artoolkit5-js?
@nicolocarpignoli maybe better create a **ES6** branch on the AR.js repo?

**Comment by nicolocarpignoli** [comment]
@MikiDi Great work, fabolous. This will be a great - a huge - enhancement.

as @kalwalt proposed, I can add you to the collaborators with write permissions, so we can follow your works better. You will have to create a branch on AR.js repo and a PR against it. Does it sound ok for you?

**Comment by kalwalt** [comment]
@nicolocarpignoli it sounds great for me! @MikiDi this will become an important step for AR.js!

**Comment by nicolocarpignoli** [comment]
@MikiDi let me know if you like the idea I will add you :)

**Comment by andypotato** [comment]
Jumping in here - First of all huge thanks @MikiDi for doing the integration work. I was planning to do that all along but never got to it due to recent time constraints. The initialization / integration is all done correctly.

About the NFT code - Yes that part is currently left blank in my code, but it's absolutely no problem to fill in the blanks as it just needs the code from [here](https://github.com/kalwalt/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/js/artoolkit.api.js#L1881) ported into my version of the lib. In addition the `addMultiMarker` method needs to be adapted in the same way.

I've already implemented a replacement for the `ajax` call as `await Utils.fetchRemoteData` and handled local file support in Emscripten so this is really straightforward to finish. If I can find some time this week I'll finish it, otherwise if you want to finish the job I can just add you as contributor - Let me know.

**Comment by MikiDi** [comment]
> As i know and as i can see from the code is not completely implemented. Not all a the methods are available yet, For example the **addNFTMarker** is not, and other...

@kalwalt Hah, clearly didn't look close enough :smile:  

> as @kalwalt proposed, I can add you to the collaborators with write permissions, so we can follow your works better. You will have to create a branch on AR.js repo and a PR against it. Does it sound ok for you?

@nicolocarpignoli Although I think in theory this would work from my fork as well, having a branch on the main repo might be clearer. I'll take care of it when you've added me. Thx for the confidence :slightly_smiling_face: :muscle: 

> About the NFT code - Yes that part is currently left blank in my code, but it's absolutely no problem to fill in the blanks as it just needs the code from [here](https://github.com/kalwalt/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/js/artoolkit.api.js#L1881) ported into my version of the lib. In addition the `addMultiMarker` method needs to be adapted in the same way.
> 
> I've already implemented a replacement for the `ajax` call as `await Utils.fetchRemoteData` and handled local file support in Emscripten so this is really straightforward to finish. If I can find some time this week I'll finish it, otherwise if you want to finish the job I can just add you as contributor - Let me know.

@andypotato Allright! I'll keep an eye on the repo ... if you don't beat me to it, I'll take care of it once I get there ... Would you mind me rewriting those methods with callbacks to return promises as well?

**Comment by kalwalt** [comment]
@MikiDi i realized that ES6 changes are only for the Aframe version, that's right?  Do you plan to do this also for Three.js?

**Comment by andypotato** [comment]
> Would you mind me rewriting those methods with callbacks to return promises as well?

Haven't looked at the code in a couple of days but I believe there are no other methods using callbacks except for the add / remove event listener methods. However these are part of an observer pattern and shouldn't be rewritten.

**Comment by nicolocarpignoli** [comment]
@MikiDi done!

**Comment by MikiDi** [comment]
> @MikiDi i realized that ES6 changes are only for the Aframe version, that's right? Do you plan to do this also for Three.js?

@kalwalt Question about this ... I've seen multiple mentions of _"using the three.js-version"._ I'm not sure what you exactly understand by this. I interpret it as "using AR.js through its api instead of through the custom aframe html-tag components". Although this is differently formulated, does that sound right?  
If this would indeed be the case, my answer to your question would be "yes, ofcourse. It is mainly the api that undergoes changes for the switch to es6."
You maybe are rather referring to the exports. If so: it indeed isn't entirely clear to me yet which classes we should export, and which ones are internal.

May be relevant: I noticed that most classes have 2 names. One in the `ARjs` namespace and one in the `THREEx` namespace ([here](https://github.com/AR-js-org/AR.js/blob/da5ea830211c323a41ebd55a97b99f85add1cd40/three.js/src/threex/threex-artoolkitcontext-nft.js#L4) for example). I couldn't really make out why this was, and supposed this was for legacy reasons, to keep backward compatibility for the old threex method names .... In the es6 rework, I made the threex ones an alias of the arjs ones, in case we would still need to export them by those names ([here](https://github.com/AR-js-org/AR.js/blob/ES6/three.js/src/threex/threex-artoolkitcontext.js) for example)

**Comment by nicolocarpignoli** [comment]
> @kalwalt Question about this ... I've seen multiple mentions of "using the three.js-version". I'm not sure what you exactly understand by this. I interpret it as "using AR.js through its api instead of through the custom aframe html-tag components". Although this is differently formulated, does that sound right?

@MikiDi absolutely correct
"AR.js three.js version" = AR.js APIs, the ones that uses directly jsartoolkit5 APIs
"AR.js aframe version" = a set of A-Frame custom components that map AR.js APIs

**Comment by kalwalt** [comment]
@MikiDi you get the point and @nicolocarpignoli simplified the concept. Ar.js provide two builds (4 in reality) : 

- ar.js and ar-nft.js (**THREEx** -> Three.js) 
- aframe-ar.js and aframe-ar-nft.js (**AR.js** -> Aframe)

**Comment by kalwalt** [comment]
Hi @MikiDi have you some updates on this PR/feature?

**Comment by MikiDi** [comment]
Hi there! I've implemented the missing methods in [artoolkit5-js](https://github.com/MikiDi/artoolkit5-js/commits/master) (untested), and started reworking the NFT part in AR.js ... nothing running yet though. Hope to report back here later this month. (I'm aware that merging the current ongoing changes is going to be a pain ... once things are working we'll have to go through the recent history manually I'm afraid)

**Comment by kalwalt** [comment]
i tested the **addNFTMarker** method in your branch i receive an error regarding **_storeDataFile** is not a function, it seems that method is not accessible in **storeMarker** function. I tried by myself in the past and had a simlar result.

**Comment by kalwalt** [comment]
@MikiDi probably it's better to use the webpack worker-loader plugin, instead to use the Blob. I had some issue with another project https://github.com/kalwalt/ARnft/issues/1#issuecomment-619802453, but maybe you solved this part in another way.

**Comment by MikiDi** [comment]
Funny that I read your comment just after implementing it that way :-D Fixed the bugs I had in artoolkit. It's coming along ... it builds and runs, but doesn't detect the T-Rex atm ... hope to clean up some more later today

**Comment by kalwalt** [comment]
> Funny that I read your comment just after implementing it that way :-D Fixed the bugs I had in artoolkit. It's coming along ... it builds and runs, but doesn't detect the T-Rex atm ... hope to clean up some more later today

Yeah, maybe some telepathic force here! I willl test if ican, Do you receive some error in the dev console?

**Comment by kalwalt** [comment]
I just tested the **aframe/examples/image-tracking/nft** . It works fine for me, it is detected and i can see the trex. You need to be very close to the image to be tracked, and consider that the trex model is a quite heavy to download. For testing maybe you can replace with a model hosted on your pc. Anyway Well done! :smile:

**Comment by MikiDi** [comment]
Hah! Better than here :smile: ... Had been wondering already if the webcam I test on is of high enough quality for image-based tracking ... Don't think that the model-size is an issue ...
So ... next steps to get this ready for merge ... exports for the "threex" classes? The more I look at it, the more I would find it logical that only the "threex"-part (the "real AR.js library") be in this repo, and that the aframe components would reside in another repo, so that eventually there would be only 1 build per repo (after having merged the NFT and non-NFT code). There's a lot to talk about ... should need to take some time to think & write out more of a plan. A call might be useful two, if you're up for that ... Will start off next week by opening a new PR, based on the ES6 branch in this repo.

**Comment by kalwalt** [comment]
> Hah! Better than here smile ... Had been wondering already if the webcam I test on is of high enough quality for image-based tracking ... Don't think that the model-size is an issue ...

i have not better devices believe me! :smile: 
> So ... next steps to get this ready for merge ... exports for the "threex" classes?

Yes, that will be nice in my opinion!

> The more I look at it, the more I would find it logical that only the "threex"-part (the "real AR.js library") be in this repo, and that the aframe components would reside in another repo, so that eventually there would be only 1 build per repo (after having merged the NFT and non-NFT code). There's a lot to talk about ... should need to take some time to think & write out more of a plan. A call might be useful two, if you're up for that ... Will start off next week by opening a new PR, based on the ES6 branch in this repo.

Two repository will mean break the AR.js project i think. Altough we could create a git submodule. I don't know How may think @nicolocarpignoli  about this problem. I would also listen also other people/devs.

**Comment by andypotato** [comment]
Just FYI, I finally came along to test @MikiDi pull request for artoolkit5-js - I can confirm it's working beautifully and merged the request into the main branch. Thanks a million for this contribution!

**Comment by andypotato** [comment]
> Hello! Is the webpack build completed? And is there anything we can do to contribute and move it further along?

The PR has been ready for quite a while but hasn't been reviewed or tested by @kalwalt or @nicolocarpignoli yet. Is there anything we can do to assist you guys?

**Comment by nicolocarpignoli** [comment]
Hi guys, unfortunately I  have no time for this. I think that @inakineitor @andypotato or others can test this by yourself.

We will create an alternative AR.js version to start, so there is no worries to break the current build.
Feel free to test and share the results here, so we can follow progresses.

**Comment by kalwalt** [comment]
@MikiDi @nicolocarpignoli  and all here, I will come back on this! i hope to have time to make a detailed review on this PR. Better to continue the discussion on the follow up PR #116 :smile:

**Comment by MikiDi** [comment]
@kalwalt Cool! Let me know if I can help out. The only thing on my virtual todo list, was to expose the "old" api classes (the ones that currently are exposed through the intermediary build). Apart from that, it will mostly be manual work to catch up with the diff that has been growing is my guess ...

**Comment by MikiDi** [comment]
The setup of a webpack-based build is being discussed further in #116 . Closing this one.

**Pull request closed without merging**
