### PR TITLE
Removing nft version in the build libs

### PR DESCRIPTION
**Pull request by kalwalt**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**

This PR will remove the double build libs (with or without nft extension). Because an issue with aframe image tracking this will be done only for threex and ar.js namespace.
**Can it be referenced to an Issue? If so what is the issue # ?**
see #402
**How can we test it?**

This still a WIP.
**Summary**

**Does this PR introduce a breaking change?**
For threex code if you want to use nft markers, you will import the `ar-threex.js` build lib instead of `ar-threex-nft.js`. That's all.
**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
Tested on desktop Ubuntu 20.04.
**Other information**
This PR also add prettier to format the code and a simple github action script to test linting. Husy with lint-staged to format the code when a new commit is created to enforce code styling.

### CODE REVIEW

**Comment by kalwalt** [comment]
As said in issue #402 the aframe nft example are not working correctly. I'm trying to catch the bug. i tested this commit 841be3ddc04daa62a1deb69d9f269c15460fb3af and the examples were working. I will continue this cehcking until i will found the bug.

**Comment by kalwalt** [comment]
version `AR.js 3.3.3-es6-beta-03` seems fine i tested also the commit 604d87992446f60e09d7a8f6859031e15f87ff1d and it's fine.

**Comment by kalwalt** [comment]
worker can't load and continue loading resources with this commit 814435d3c3d25342fd109960dd814b76ef1005b4 So someting wrong when adding the event listener or initializig the arContext.

**Comment by kalwalt** [comment]
from twitter: https://twitter.com/githubstatus/status/1504526048591073293?s=20 seems some problems with github action

**Comment by kalwalt** [comment]
Now the action script run successfully the test script!

**Comment by kalwalt** [comment]
The README file need to be updated about which lib files to use for the different namespaces and nft or if location based or not. Will do this as well.

**Comment by kalwalt** [comment]
@nickw1 i will merge this as it will fix some important bugs and add prettier to format the code. When it will be merged we need to test if formatting works when every commit is created. We need also to format code after this PR. Prettier will format the code only .js files for now. We can include also other types (.css html md) but we can do in another step. Probably we can change the prettier configuration, to format the code in a better way, if you have some suggestions let me know.

**Comment by nickw1** [comment]
@kalwalt ok looks good. No suggestions just yet but will see what results the code formatting produces.

**Comment by kalwalt** [comment]
I think we need to update also the AR-js-docs because are not updated with the latest changes.

**Pull request merged**
