### PR TITLE
Projected-Based GPS Camera: example and updating Docs

### PR DESCRIPTION
**Pull request by nicolocarpignoli**
Follows https://github.com/AR-js-org/AR.js/pull/75

- [x] Add at least one example using new projected gps camera component
- [x] Update AR.js official Docs

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@nickw1 I will give you access so you can work directly on this branch on AR.js repo, also I will give you access to AR.js-Docs repository: https://github.com/AR-js-org/AR.js-Docs

You can open a branch + related PR also on there when you want :)

**Comment by nickw1** [comment]
@nicolocarpignoli OK thanks! Will put together an example and work on some docs.

**Comment by nickw1** [comment]
@nicolocarpignoli Basic example now up, hard-coded location and three projected entity-places. Will work on docs and try to put together a more complex example using openstreetmap data. Will keep you updated!

**Comment by nickw1** [comment]
@nicolocarpignoli OK now have two examples, a basic one (as I mentioned the other day) and one which downloads OpenStreetMap data from an API and renders it as AR content. I've also added some docs to a 'projecred-based-example' branch in the docs repo.

**Comment by nicolocarpignoli** [comment]
@nickw1 basic example is ok, the other one I fixed something (see my commit) and changed some indentation, cosmetic stuff. But: it's stuck on 'Loading OSM data...'. Can you check please?

**Comment by nickw1** [comment]
@nicolocarpignoli  ok thanks for the cleanup.
The bundle.js was actually intentional; to run the example you have to build it with browserify (the provided makefile does this) and then include the resulting bundle.js. Maybe I need to add a README to clarify this :-)

**Comment by nicolocarpignoli** [comment]
@kalwalt are you able to give a look at this and try it? I have very poor time these period unfortunately

**Comment by nicolocarpignoli** [comment]
Or someone else, any help is welcome

**Comment by kalwalt** [comment]
@nicolocarpignoli i would do, i tried the example in the issue time ago.i will let you know.

**Comment by nicolocarpignoli** [comment]
looks good to me. Great great job @nickw1 thank you again! merging and going to release this

**Pull request merged**
