### PR TITLE
Use smoothing to reduce shaking effect

### PR DESCRIPTION
**Pull request by nickw1**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**

Feature; considerably reduces the shaking effect when holding device still. 

**Can it be referenced to an Issue? If so what is the issue # ?**
#139 

**How can we test it?**

Note that you cannot use the `<a-camera>` tag as this automatically injects the default `look-controls`. So you have to create an `<a-entity>` with a `camera` component, as well as `arjs-look-controls`.

So for example:
`<a-entity id='camera1' camera='near:0.1; far:50000; fov:80;' arjs-look-controls='smoothingFactor: 0.1' gps-projected-camera='gpsMinDistance: 5' ... >`
**Summary**

Considerably reduces the shaking effect when holding device still. It does this by applying smoothing to the raw orientation values.

To do this, I created a custom `look-controls` component entitled `arjs-look-controls` to replace the default one. This approach is recommended in the A-Frame documentation, see [here](https://aframe.io/docs/1.0.0/components/look-controls.html). The component uses `THREE.DeviceOrientationControls` which itself has been modified to add smoothing. The `arjs-look-controls` component has a `smoothingFactor` property to control the amount of smoothing.

A smoothed orientation is essentially defined by:
`smoothedOrientation  = smoothingFactor * currentValue + (1-smoothingFactor) * previousSmoothedValue`

so it can be seen that the lower the smoothing factor (in range 0 to 1), the more smoothing applies. In tests 0.1 seems to work well whereas 0.05 smooths a little too much.

**Does this PR introduce a breaking change?**

No. Code to test for `arjs-look-controls` has been added to `gps-camera` and `gps-projected-camera` but it falls back to `look-controls` if not available.

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**

Pixel 3, Android 10, Chrome.

**Other information**

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
I have imported your AR.js version => https://rawcdn.githack.com/nickw1/AR.js/0832a20bf39cde18e71df9b2e3d77f6a23a56aea/aframe/build/aframe-ar-nft.js

on an AR.js example, and used:

`<a-entity  gps-camera="minDistance: 50; positionMinAccuracy: 300; gpsMinDistance: 5;" rotation-reader ></a-entity>`

I see no places rendered. The problem is the 'a-entity' tag. If I use

`<a-camera  gps-camera="minDistance: 50; positionMinAccuracy: 300; gpsMinDistance: 5;" rotation-reader ></a-camera>
`

works okay, of course without the shaking fix. What can be the problem?

**Comment by nicolocarpignoli** [comment]
Places are added to the DOM using JS. Maybe some event is not fired correctly? Do you have tested with AR.js examples?

**Comment by nickw1** [comment]
Have you tried adding the `camera` component?  In other words something like:

`<a-entity camera='near:0.1; far: 50000' gps-camera="minDistance: 50; positionMinAccuracy: 300; gpsMinDistance: 5;" rotation-reader></a-entity>`

**Comment by nickw1** [comment]
I am however finding an issue on further testing - the augmented content is not oriented correctly in landscape mode. This is only with the new `arjs-look-controls` component; it works ok with the directly edited A-Frame build. Will need to investigate this, difficult to see why on first look.

**Comment by nicolocarpignoli** [comment]
Unfortunately I still cannot see any gps-entity-place. Can you please try this code? (adding your latitude/longitude of course)

```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>GeoAR.js demo</title>
    <script src='https://aframe.io/releases/1.0.4/aframe.min.js'></script>
    <script src="https://rawcdn.githack.com/nickw1/AR.js/553a5a8a846de6b772175da88886ed878b9cca22/aframe/build/aframe-ar-nft.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
</head>

<body style='margin: 0; overflow: hidden;'>
    <a-scene
        vr-mode-ui="enabled: false"
		embedded
		arjs='sourceType: webcam; debugUIEnabled: false;'>

        <a-box material="color: red;" scale="15 15 15" gps-entity-place="latitude: <value> longitude: <value>;"></a-box>

        <a-entity camera='near: 0.1; far: 50000;'
            gps-camera="gpsMinDistance: 5;"
            arjs-look-controls='smoothingFactor: 0.1'
            rotation-reader>
        </a-entity>
	</a-scene>
</body>

```

The problem is not with the arjs-look-controls but with using the 'a-entity' tag.

**Comment by nickw1** [comment]
OK looks like there is an issue with the ordering of components. The `look-controls` or `arjs-look-controls` has to come before the `gps-camera`, actually that makes sense as the first thing that `gps-camera` does is check for the existence of a `look-controls` component. If I change the order then the cube appears.

Then it works, though with the basic example I'm getting occasional 'jerky' movement if you move the device too fast. However this is likely to be an issue with the smoothing code and is probably relatively easily fixed.

See https://hikar.org/webapp/test.html.

Maybe there's a way of using `<a-camera>` but telling it to not inject the default `look-controls` component. Will try and look into this.

**Comment by nickw1** [comment]
... Yes, you can do it. `<a-camera look-controls-enabled='false' .... >`

**Comment by nicolocarpignoli** [comment]
That's better so we do not have to change a lot of documentation :)

**Comment by nickw1** [comment]
Now merging this. There is still an unresolved issue with 'jerky' effects when moving the camera, which appears to relate to the beta angle in landscape or gamma in portrait. Nonetheless the overall effect, with 'shaking' much reduced, is an improvement on before. Also the feature can be turned on or off with the use, or non-use, or `arjs-look-controls`.

**Comment by nicolocarpignoli** [comment]
Absolutely agree.

**Comment by ThomasRutzer** [comment]
Hi,

I also tested the `arjs-look-controls` today and can confirm, that the overall marker stability improved greatly (Samsung s20/Chrome for Android v86). 
But with the "jerky"-effect, do you mean that sometimes the `gps-entity-place` suddenly moves out / in again? This is sth I observed multiple times. Do you have any idea what to do about it?

Nevertheless, I'm also exploring to smooth the `heading`-values with simple average mean function. And it seems to improve stability even more but of course reduces accuracy.

**Pull request merged**
