### PR TITLE
Using SimulateAltitude parameter separately from latitude and longitude

### PR DESCRIPTION
**Pull request by NVFedorov**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**
This PR is introducing new feature: simulating altitude separately from latitude and longitude. So now developers can "lock" altitude and don't rely on ```navigator.geolocation```

**Can it be referenced to an Issue? If so what is the issue # ?**
#167 
**How can we test it?**

Test project created: https://glitch.com/~kindly-verbena-loan

**Summary**

Previously it wasn't possible to adjust Y position of an entity without taking into account altitude provided by ```navigator.geolocation``` API. The altitude determination process may be very inaccurate and depends on lots of factors (i.e. surrounding landscape).

**Does this PR introduce a breaking change?**
No

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**
Xiaomi Redmi Note 6 Pro, Adroid 9, Chrome 76.0.3809.89

**Other information**

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@nickw1 It looks okay to me, what do you think? Should not break anything.

**Comment by nickw1** [comment]
@nicolocarpignoli seems fine to me. Shall I merge it?

**Comment by nicolocarpignoli** [comment]
Yes ;)

**Comment by nickw1** [comment]
OK. It need a little more work than anticipated because the PR conflicts with the recent changes for `gpsMinDistance`. Will look at this later.

**Comment by nickw1** [comment]
@NVFedorov have now merged your pull request. Note I had to edit your code a little to resolve some conflicts that had arisen from dev being updated since you forked the repository. Let myself or @nicolocarpignoli know if there are any problems.

**Comment by NVFedorov** [comment]
cool, thank you guys! This is my first contribution to open source :)

**Pull request merged**
