### PR TITLE
Three location based enhancements

### PR DESCRIPTION
**Pull request by nickw1**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**

New features for three location based including improved GPS error handling, API consistency between real and fake GPS locations, and user-definable accuracy and distance thresholds.

**Can it be referenced to an Issue? If so what is the issue # ?**

**How can we test it?**

Available online at:
https://hikar.org/thrloc/three.js/examples/location-based/

**Summary**

Enhanced functionality for the three.js location-based feature. Includes:
- `gpserror` event emitted if there was a GPS error.
- common behaviour for real and fake GPS updates, so you can handle both with the `gpsupdate` event
- configurable minimum GPS accuracy and minimum distance moved to trigger a GPS update.

Note that this is the three.js part of PR #406 (enhanced A-Frame location-based components), separated out as it might be nice to include this in the next `rc2` release.

**Does this PR introduce a breaking change?**

No

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**

Chrome, Firefox Linux desktop (real and fake GPS tested)
Chrome on Android 12 / Pixel 3

**Other information**

### CODE REVIEW

**Comment by kalwalt** [comment]
@nickw1 i will test tomorrow evening, i have no time today, i'm busy with my job... but without testing, just reading the code, seems ok to me.

**Comment by kalwalt** [comment]
@nickw1 I tested with my Android device (GPS enabled of course) but i can see the boxes only in the FakeGps mode, Did worked for you?

**Comment by nickw1** [comment]
@kalwalt yes definitely works for me with real GPS on a real mobile device.

Wondering if it's anything to do with the default min GPS accuracy? This is set at 30m so if the GPS error is greater than 30m then the location will not update.

You can specify this with the `gpsMinAccuracy` option e.g.

```javascript
const arjs = new THREEx.LocationBased(scene, camera, { gpsMinAccuracy: 100 } ); 
```

will increase the min accuracy to 100m. Does this fix it?

**Comment by kalwalt** [comment]
> @kalwalt yes definitely works for me with real GPS on a real mobile device.
> 
> Wondering if it's anything to do with the default min GPS accuracy? This is set at 30m so if the GPS error is greater than 30m then the location will not update.
> 
> You can specify this with the `gpsMinAccuracy` option e.g.
> 
> ```js
> const arjs = new THREEx.LocationBased(scene, camera, { gpsMinAccuracy: 100 } ); 
> ```
> 
> will increase the min accuracy to 100m. Does this fix it?

Ok @nickw1 i would check the error accuracy. It could be because i'm testing in a old building with very tick walls. Let me make a quick test. :smile:

**Comment by kalwalt** [comment]
I tested with `const threex = new THREEx.LocationBased(scene, camera, { gpsMinAccuracy: 1000 } ); ` and it worked for me, Instead `gpsMinAccuracy: 100` was not sufficient. Maybe we can add a comment in the code about this?

**Comment by kalwalt** [comment]
I merged the #407 i think you need to pull latest changes from dev, install latest dependencies with `npm install` and try a `npm run format`  to format the new code. When you commit husky should run another time prettier.

**Comment by nickw1** [comment]
@kalwalt OK will do. Maybe I will increase the default min accuracy to a value that is likely to work for testing (e.g. 1000), and add a comment in the example to show people how to change the accuracy.

I chose 30m because in my experience that is the 'worst' accuracy a GPS device has when still in-signal, but looks like maybe it needs to be higher.

**Comment by kalwalt** [comment]
> @kalwalt OK will do. Maybe I will increase the default min accuracy to a value that is likely to work for testing (e.g. 1000), and add a comment in the example to show people how to change the accuracy.
> 
> I chose 30m because in my experience that is the 'worst' accuracy a GPS device has when still in-signal, but looks like maybe it needs to be higher.

I always tested in an indoor environment, that is quite difficult situation, i will try to test outdoor and for sure it will be better. But i think other people could have this issue too. i usually test with my desktop computer and then with my Android device in localhost. 
Of course 30m is the worst accuracy, but this is not intended as a ready production product, just an example. Maybe 1000 is too much but we can see in a near future how to improve it.

**Comment by kalwalt** [comment]
After that, if you make last changes we can merge i think. What do you think?

**Comment by nickw1** [comment]
@kalwalt yes sounds good. Will merge now.

**Comment by kalwalt** [comment]
This evening i will merge the dev branch on master and will release a new version `3.4.0-alpha-rc2`.🙂

**Comment by nickw1** [comment]
@kalwalt ok great! Incidentally what release are we planning #406 for? This will need quite a bit of testing but hopefully will solve some of the problems people have been having with A-Frame location based.

**Comment by kalwalt** [comment]
> @kalwalt ok great! Incidentally what release are we planning #406 for? This will need quite a bit of testing but hopefully will solve some of the problems people have been having with A-Frame location based.

Sorry i forgot that, haven't tested yet, could we release together? or we need more testing and we make another release?

**Comment by nickw1** [comment]
I've tested on desktop Linux and on Android/Chrome and works on both.
Not tested on iOS or any other platform.

So do you want to test? Happy for you to release rc2 now and then include this in rc3 in a few days, or whatever. Or, if you prefer, happy to delay rc2 until you've tested.

Whichever you would like to do, I might tweak it a little to ensure it's compatible with #410.

**Comment by kalwalt** [comment]
@nickw1 i will release rc2 without changes regarding #406. I have an issue we will discuss there. I think it's better to make now a release instead of delaying. There is a important fix for a bug in aframe nft with image tracking that i prefer to public as soon as possible.

**Comment by nickw1** [comment]
@kalwalt ok great!

**Pull request merged**
