### PR TITLE
Removed PR #560 from master, present in dev

### PR DESCRIPTION
**Pull request by nickw1**
PR #560 merge was intended for dev, unintentionally added to master.

### CODE REVIEW

**Comment by nickw1** [comment]
Hi @kalwalt, PR #560 was inadvertently merged into master, should have been only in dev. I've reverted the changes in the PR with this new PR #610, in order to keep master clean. Are you able to approve this revert? Thanks.

**Review by kalwalt — COMMENTED** [review]
Reading the code, I think you correctly reverted the code.

**Comment by nickw1** [comment]
@kalwalt Great, can you review the PR? (I am unable to merge without an approving review).

Thanks.

**Review by kalwalt — APPROVED** [review]
All is fine! it can be merged.

**Comment by nickw1** [comment]
@kalwalt Many thanks - done!

**Comment by nickw1** [comment]
@kalwalt sorry, I've noticed that the CI is failing due to master being a protected branch. It also reports that "changes must be made through a pull request".

https://github.com/AR-js-org/AR.js/actions/runs/11581567636/job/32242622440

The odd thing is that it has actually merged the PR successfully.

Do we want to un-protected the master branch temporarily just to get the CI to work, otherwise it looks to people browsing the repo that something is wrong?

**Comment by kalwalt** [comment]
> @kalwalt sorry, I've noticed that the CI is failing due to master being a protected branch. It also reports that "changes must be made through a pull request".
> 
> https://github.com/AR-js-org/AR.js/actions/runs/11581567636/job/32242622440
> 
> The odd thing is that it has actually merged the PR successfully.
> 
> Do we want to un-protected the master branch temporarily just to get the CI to work, otherwise it looks to people browsing the repo that something is wrong?

This Is odd, i will look into It this evening.🙂

**Comment by kalwalt** [comment]
The only way to solve this was, as you suggested, to temporary unset the `master` branch protection rule, probably a bug with the EndCommit github action packagage or something related. I will open an issue to keep track of this.

**Pull request merged**
