### PR TITLE
update videohandler in nft-video example

### PR DESCRIPTION
**Pull request by JamesBotterill**
**⚠️ All PRs have to be done versus 'dev' branch, so be aware of that, or we'll close your issue ⚠️**

**What kind of change does this PR introduce?**
Adding a event to stop and reset video on marker lost within videohandler 

**Can it be referenced to an Issue? If so what is the issue # ?**

**How can we test it?**

**Summary**

This is purely to expand on the videohandler component to handle the video being lost to stop and reset 

**Please TEST your PR before proposing it. Specify here what device you have used for tests, version of OS and version of Browser**

**Other information**

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
@JamesBotterill please align your branch with dev, I see some modifies files that should not be modified in this PR

**Comment by kalwalt** [comment]
@nicolocarpignoli maybe AR.js master is ahead of dev?

**Comment by nicolocarpignoli** [comment]
no I aligned it

**Comment by JamesBotterill** [comment]
Not a problem, I'll close this and create a new PR from dev branch

**Pull request closed without merging**
